theme = "gruber-darker"

[editor]
cursorline = true
rulers = [80]
bufferline = "multiple"
color-modes = true
true-color = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator"
]
center = ["diagnostics"]
right = ["file-type", "selections", "position"]
